version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-geral
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker-compose:/etc/nginx/conf.d
    networks:
      - chama


networks:
  chama:
    driver: bridge 
    external: true 